### PR TITLE
Strip windows binaries directly on Windows

### PR DESCRIPTION
**Pull request by Luni-4**
Simplify the code stripping windows binaries directly on `Windows`

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by dwbuiten** [comment]
Actually, is it even valid to strip MSVC binaries? I didn't think it was... but maybe I am misremembering.

**Comment by Luni-4** [comment]
They should be stored in the pdb file, so actually it could be useless. But I suppose we are not doing something wrong running the `strip` command on them the same.

**Comment by Luni-4** [comment]
@dwbuiten 
Do not strip `msvc` binaries

**Comment by Luni-4** [comment]
> Thanks. The reason I asked is because I have vague memories of `strip` causing malformed binaries when using it on MSVC-built things. I don't know if it is still true or not, but no reason to not play it safe.
> 
> LGTM.

Thanks to  you for the review! :)

**Pull request merged**
