### PR TITLE
Add datadir support

### LINKED ISSUE #184: Architecture independent install files support
I want support for installing architecture independent files. For instance, I have a usecase to install configuration file under /usr/local/share/myproject/.

Once datadir is supported, it should be easy to add infodir, mandir, localedir etc other common shared files support.
c.f. https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html

### PR DESCRIPTION
**Pull request by lu-zero**
Fixes #184

### CODE REVIEW

**Comment by naokiri** [comment]
@lu-zero  Yes, this looks really nice. I really appreciate this feature.

**Comment by lu-zero** [comment]
@naokiri did you find time to test it?

**Comment by naokiri** [comment]
Sorry I was busy and couldn't respond for a while.

For my use case I was using other configurations name for directory names and I needed a similar configuration like this PR
https://github.com/lu-zero/cargo-c/pull/237

**Comment by lu-zero** [comment]
Let me land this and then add upon it.

**Pull request merged**
