### PR TITLE
Unbreak .def generation

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by lu-zero** [comment]
@cpu could you please try this and report back?

**Comment by cpu** [comment]
@lu-zero I built/installed this branch and it worked great for my example-ffi test repo :tada: Thanks for the very quick fix.

**Comment by cpu** [comment]
>  it worked great for my example-ffi test repo

And for what it's worth, also for `rustls-ffi`, where I started down this road originally 🔒

**Comment by lu-zero** [comment]
Good to know, in case other problems arise:
- https://github.com/mstorsjo/msvc-wine is a boon
- https://github.com/rust-cross/cargo-xwin is also quite interesting to setup a msvc toolchain
- we could copy more mingw-w64 `gendef`

**Comment by cpu** [comment]
>  in case other problems arise:

Thanks for sharing these resources :bow:

**Pull request merged**
