### PR TITLE
CI: Add "cargo ctest"

### PR DESCRIPTION
**Pull request by mgeier**
This is marked as "draft" because it doesn't seem to run successfully on Windows.

### CODE REVIEW

**Comment by lu-zero** [comment]
The problem with linking could be probably solved in `inline-c`. please open an issue on their side as well.

**Comment by mgeier** [comment]
I don't know anything about linking on Windows, can you please do that?

**Comment by lu-zero** [comment]
I found a workaround, please rebase and we'll land it.

**Comment by mgeier** [comment]
Thanks @lu-zero, now the tests pass!

**Pull request merged**
