### PR TITLE
Add support for overriding pkg-config name/description/version

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/lu-zero/cargo-c/issues/12

### CODE REVIEW

**Comment by lu-zero** [comment]
I'll test sled, nnnoiseless and rav1e in a bit (or tomorrow) and then I'll land it.

**Comment by sdroege** [comment]
Ok, thanks :) I tested with nnnoiseless and it looked good to me (no change), but please double-check.

For that one I also wonder if it wouldn't make sense to rename the pkg-config file and other things so it is really a drop-in replacement for rnnoise. Currently it provides the same API/ABI, but that's about it. @jneem what do you think?

**Comment by lu-zero** [comment]
You want to have different library name and different pkg-config name so you can install both at the same place. Ideally we could/should add the overrides to the command line as well ^^;

**Comment by lu-zero** [comment]
(once https://github.com/clap-rs/clap/pull/1878 is complete it would be incredibly simple to override from cli)

**Comment by sdroege** [comment]
> You want to have different library name and different pkg-config name so you can install both at the same place. Ideally we could/should add the overrides to the command line as well ^^;

But if the pkg-config name is different, how would existing software pick up nnnoiseless instead of rnnoise without changes in their build system?

**Comment by lu-zero** [comment]
The open question is who is picking. I'd give the option to pass the override from the cli to allow all the options (replace completely or allow side-by-side install).

The default should be non-colliding IMHO.

**Comment by jneem** [comment]
My inclination is to require opt-in for replacing rnnoise with nnnoiseless, especially if it's just a matter of changing `pkg-config rnnoise` to `pkg-config nnnoiseless`.

**Pull request merged**
