### PR TITLE
Use Vec::extend instead of a side-effect-only Option::map

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by cuviper** [comment]
I cited this as an example in https://github.com/rust-lang/rust/issues/71484, which is asking for `#[must_use]` on `Option::map`.

**Comment by cuviper** [comment]
Another possibility could avoid the `Vec`, if you like:

```rust
    let paths = iter::once(&build_targets.include)
        .chain(&build_targets.static_lib)
        .chain(&build_targets.shared_lib);
```

**Comment by cuviper** [comment]
There's a little magic in leveraging `IntoIterator for &Option<T>` here.

**Comment by lu-zero** [comment]
yes, thus why it is a bit surprising, but overall looks compact and I like the expressiveness.

**Pull request merged**
