### PR TITLE
Deploy cargo-c binaries

### LINKED ISSUE #70: Add a CI deploy target
- [ ] add macOS builds as the release artifacts
- [ ] add Windows builds as the release artifacts
- [ ] add Linux builds as the release artifacts

### PR DESCRIPTION
**Pull request by Luni-4**
This PR fixes #70

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by dwbuiten** [comment]
Which windows toolchain does this use? We should arguably provide both, because e.g. most users of some projects like Rav1e would want to build with the GNU ABI, since its main use is in FFmpeg (and mostly all FFmpeg on windows is MinGW).

**Comment by lu-zero** [comment]
> Which windows toolchain does this use? We should arguably provide both, because e.g. most users of some projects like Rav1e would want to build with the GNU ABI, since its main use is in FFmpeg (and mostly all FFmpeg on windows is MinGW).

The default toolchain is a local configuration and should not depend on how the tool is built IIRC.

Should be tested though.

**Comment by Luni-4** [comment]
I've added both the Windows toolchains for now

**Comment by lu-zero** [comment]
you should rebase it I guess.

**Pull request merged**
