### PR TITLE
don't rebuild pc file if cache has not been invalidated

### LINKED ISSUE #104: Rebuilds pkg-config file on `cbuild` and `cinstall`
```
$ cargo cbuild --prefix=(pwd)/install
   Compiling ebur128 v0.1.1 (/home/slomo/Projects/rust/ebur128)
    Finished dev [optimized + debuginfo] target(s) in 2.84s
    Building pkg-config file
$ cargo cinstall --prefix=(pwd)/install
    Finished dev [optimized + debuginfo] target(s) in 2.02s
    Building pkg-config file
  Installing pkg-config file
  Installing header file
  Installing static library
  Installing shared library
```

It seems like it also re-links (or even rebuilds) the library itself. If this can't be reproduced with anything else then I'll debug this / provide a testcase in a bit.

### PR DESCRIPTION
**Pull request by gdesmott**
Fix #104

### CODE REVIEW

**Comment by gdesmott** [comment]
Actually that's not enough. We need to trigger a rebuild if the cli arguments such as  `--prefix` have changed as well.

**Comment by sdroege** [comment]
> Actually that's not enough. We need to trigger a rebuild if the cli arguments such as `--prefix` have changed as well.

And probably also if some of the configuration from `Cargo.toml` has changed

**Comment by lu-zero** [comment]
Yes, fingerprint() probably needs to be extended a bit to make it work reliably for this use-case ^^;

**Comment by gdesmott** [comment]
> We need to trigger a rebuild if the cli arguments such as `--prefix` have changed as well.

What would the proper way to do that? We have two options here:
- parse the existing `.pc` file and check if its prefix, libdir, etc matches the one passed on the cli.
- Hash the CLI arguments (`InstallPaths`) as well when generating the fingerprint and store it in the target directory.

@lu-zero : which option do you prefer?

**Comment by lu-zero** [comment]
Historically in the previous implementation we did the latter and worked sort of fine.

**Comment by gdesmott** [comment]
Ok, what about this then? It no longer regenerate everything when rebuilding the Rust gst plugins.

> And probably also if some of the configuration from `Cargo.toml` has changed

Looks like any change in `Cargo.toml` triggers a rebuild so we should be good.

**Comment by lu-zero** [comment]
Looks good beside the small problem clippy found. I guess once you address it it is good to go.

**Comment by gdesmott** [comment]
Should be good now.

**Review by lu-zero — APPROVED** [review]
Looks good to me :)

**Pull request merged**
