### PR TITLE
Use CC to find dumpbin

### LINKED ISSUE #147: dumpbin is not in the PATH by default
I'm currently trying to add cargo-c to a project and I'm compiling with MSVC.

The problem is that `dumpbin` is not in the PATH by default. This has been mentioned in  #113 and added in #71.

I've the following error:
```
    Building pkg-config file
    Building .def file using dumpbin
Error: CliError { error: Some(The system cannot find the file specified. (os error 2)), exit_code: 101 }
```

As a workaround I could add `dumpbin` manually to the PATH, which I find ugly. Or maybe use a `build.rs` to find `dumpbin` and add it to the PATH, which is not ideal too.

Maybe the linker path information obtained from cargo can be used since (at least for VS 2019) `dumpbin.exe` is in the same directory as `link.exe` and `cl.exe` ?

### PR DESCRIPTION
**Pull request by Mikayex**
Fixes #147

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]
Looks great, thank you!

**Comment by mgeier** [comment]
Since this is only used on Windows, shouldn't the dependency only be installed on Windows?

See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies.

**Comment by lu-zero** [comment]
I plan to use it to add support to build C examples out of box. Hopefully it would not take much time. :)

**Comment by mgeier** [comment]
OK, but then it would only be a "dev" dependency, right?

**Comment by lu-zero** [comment]
No, it will be used for `cargo cbuild --examples` :)

**Pull request merged**
