### PR TITLE
Travis: Add basic testing and coverage

### LINKED ISSUE #15: Add some minimal CI
- [ ] Setup Travis
- [ ] Setup kcov

### PR DESCRIPTION
**Pull request by 1480c1**
Closes #15

### CODE REVIEW

**Comment by 1480c1** [comment]
Still making sure it's correct.

To actually activate coveralls.io, you would have to go to <https://coveralls.io> and add repo

**Comment by lu-zero** [comment]
Thank you :)

**Comment by lu-zero** [comment]
coveralls times out on install apparently.

**Comment by 1480c1** [comment]
Trying to figure out what's wrong

**Comment by 1480c1** [comment]
Decided to manually install kcov instead of using the script since that seemed to not always work. Should be fixed now

**Comment by 1480c1** [comment]
Would it be possible to add more tests? particularly for static_libs.rs and main.rs

**Comment by lu-zero** [comment]
I'd like to have an integration test so we are sure cargo-c keeps producing the same files, but might be a bit more involving.

**Comment by 1480c1** [comment]
That is true

**Comment by lu-zero** [comment]
Let's land this first and then add more tests :)

**Pull request merged**
